/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedLaddersIndexRouteImport } from './routes/_authed/ladders/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedLaddersRulesRouteImport } from './routes/_authed/ladders/rules'
import { Route as AuthedLaddersLadderIdIndexRouteImport } from './routes/_authed/ladders/$ladderId/index'
import { Route as AuthedLaddersLadderIdPlayerPlayerIdIndexRouteImport } from './routes/_authed/ladders/$ladderId/player.$playerId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaddersIndexRoute = AuthedLaddersIndexRouteImport.update({
  id: '/ladders/',
  path: '/ladders/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLaddersRulesRoute = AuthedLaddersRulesRouteImport.update({
  id: '/ladders/rules',
  path: '/ladders/rules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaddersLadderIdIndexRoute =
  AuthedLaddersLadderIdIndexRouteImport.update({
    id: '/ladders/$ladderId/',
    path: '/ladders/$ladderId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLaddersLadderIdPlayerPlayerIdIndexRoute =
  AuthedLaddersLadderIdPlayerPlayerIdIndexRouteImport.update({
    id: '/ladders/$ladderId/player/$playerId/',
    path: '/ladders/$ladderId/player/$playerId/',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/ladders/rules': typeof AuthedLaddersRulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ladders': typeof AuthedLaddersIndexRoute
  '/ladders/$ladderId': typeof AuthedLaddersLadderIdIndexRoute
  '/ladders/$ladderId/player/$playerId': typeof AuthedLaddersLadderIdPlayerPlayerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/ladders/rules': typeof AuthedLaddersRulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ladders': typeof AuthedLaddersIndexRoute
  '/ladders/$ladderId': typeof AuthedLaddersLadderIdIndexRoute
  '/ladders/$ladderId/player/$playerId': typeof AuthedLaddersLadderIdPlayerPlayerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/ladders/rules': typeof AuthedLaddersRulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/ladders/': typeof AuthedLaddersIndexRoute
  '/_authed/ladders/$ladderId/': typeof AuthedLaddersLadderIdIndexRoute
  '/_authed/ladders/$ladderId/player/$playerId/': typeof AuthedLaddersLadderIdPlayerPlayerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/ladders/rules'
    | '/api/auth/$'
    | '/ladders'
    | '/ladders/$ladderId'
    | '/ladders/$ladderId/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/ladders/rules'
    | '/api/auth/$'
    | '/ladders'
    | '/ladders/$ladderId'
    | '/ladders/$ladderId/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/_authed/ladders/rules'
    | '/api/auth/$'
    | '/_authed/ladders/'
    | '/_authed/ladders/$ladderId/'
    | '/_authed/ladders/$ladderId/player/$playerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ladders/': {
      id: '/_authed/ladders/'
      path: '/ladders'
      fullPath: '/ladders'
      preLoaderRoute: typeof AuthedLaddersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/ladders/rules': {
      id: '/_authed/ladders/rules'
      path: '/ladders/rules'
      fullPath: '/ladders/rules'
      preLoaderRoute: typeof AuthedLaddersRulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ladders/$ladderId/': {
      id: '/_authed/ladders/$ladderId/'
      path: '/ladders/$ladderId'
      fullPath: '/ladders/$ladderId'
      preLoaderRoute: typeof AuthedLaddersLadderIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ladders/$ladderId/player/$playerId/': {
      id: '/_authed/ladders/$ladderId/player/$playerId/'
      path: '/ladders/$ladderId/player/$playerId'
      fullPath: '/ladders/$ladderId/player/$playerId'
      preLoaderRoute: typeof AuthedLaddersLadderIdPlayerPlayerIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedLaddersRulesRoute: typeof AuthedLaddersRulesRoute
  AuthedLaddersIndexRoute: typeof AuthedLaddersIndexRoute
  AuthedLaddersLadderIdIndexRoute: typeof AuthedLaddersLadderIdIndexRoute
  AuthedLaddersLadderIdPlayerPlayerIdIndexRoute: typeof AuthedLaddersLadderIdPlayerPlayerIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedLaddersRulesRoute: AuthedLaddersRulesRoute,
  AuthedLaddersIndexRoute: AuthedLaddersIndexRoute,
  AuthedLaddersLadderIdIndexRoute: AuthedLaddersLadderIdIndexRoute,
  AuthedLaddersLadderIdPlayerPlayerIdIndexRoute:
    AuthedLaddersLadderIdPlayerPlayerIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
